package ppois.lb2;

public enum SpecializationForArchitect {
    LANDSCAPE_ARCHITECTURE, ARCHITECTURE_OF_RESIDENTIAL_BUILDINGS, COMMERCIAL_ARCHITECTURE, URBAN_PLANNING,
    INDUSTRIAL_ARCHITECTURE
}

